export const onboardingScreenOne = "/svg/onboarding-screen-one.svg"
export const ShieldSvg = "/svg/shield.svg"
export const DataSvg = "/svg/data.svg"
export const CrownSvg = "/svg/crown.svg"
export const EyeClosed = "/svg/eye-closed.svg"
export const CryptoTradingBot = "/svg/crypto-trading-bot.svg"
export const HedgeFund = "/svg/hedge-fund.svg"
